### ISSUE TITLE
Don't airgap your system

### ISSUE THREAD

**Issue by kossLAN** [NotAShelf/nyx#47]
I notice you are air-gapping this system, personally I want to live in your system so please open it for me.  Also, If at all possible please open an ssh server and give me your root password and IP address as well, please and thank you. 

[Issue in file](https://github.com/NotAShelf/nyx/blob/main/hosts/erebus/system/default.nix)

Making these changes would allow me to easily access your pc as I want to.
`
  networking = {
    wireless.enable = true;
    dhcpcd.enable = true;
  };
`

**Comment by NotAShelf** [comment]
I'm sorry but connecting that host to the internet actually makes it combust violently. Could you test locally and send me a patch?

**Comment by kossLAN** [comment]
Personally that would be kind of like me doing the work, I'd rather have you test it and code and do it so I don't need to. After all this your flake. Thus, you should take responsibility and time out of your day to fix my issue.

**Comment by NotAShelf** [comment]
good point

but unfortunately

nuh uh
