### ISSUE TITLE
Low latency setup not working?

### ISSUE THREAD

**Issue by VeilSilence** [NotAShelf/nyx#67]
Greetings. 
I'm a newbie in NixOS, so I am bit clueless about how thing work on NixOS. 

As title says, low latency setup not working at all, or at least for me? 
[Initially, I followed the low-latency setup outlined in the official wiki. I set the quantum to 64 for example. ](https://wiki.nixos.org/wiki/PipeWire#Low-latency_setup)
After `nh os switch`, I did `pw-top` to check my quant level. In the QUANT column, `pw-top` show  2048 instead of 64.

For instance, when I ran `pw-metadata -n settings 0 clock.force-quantum 64`, it successfully changed to 64 in `pw-top`.
I began to wonder if I misunderstood something in the wiki, so I decided to try your low-latency setup, but encountered the same issue in the end.
I inspect your low-latency setup closely, and noticed this:
```nix
 wireplumber = {
          enable = true;
          configPackages = let
            # generate "matches" section of the rules
            matches = toLua {
              multiline = false; # looks better while inline
              indent = false;
            } [[["node.name" "matches" "alsa_output.*"]]]; # nested lists are to produce `{{{ }}}` in the output

            # generate "apply_properties" section of the rules
            apply_properties = toLua {} {
              "audio.format" = "S32LE";
              "audio.rate" = rate * 2;
              "api.alsa.period-size" = 2;
            };
``` 
After a bit of research, I found that [the configuration file format changed in 0.5 version Wireplumber. Lua no longer supported by it.](https://pipewire.pages.freedesktop.org/wireplumber/daemon/configuration/migration.html#config-migration)

Maybe you can provide assistance about this? Is `pw-top` show correct `quant` on your side? Do I misunderstand something?

 Your flake looks amazing btw, much more useful than nix wiki, so that's why I decide to ask here about this. 
 Thank you so much for this amazing flake.

**Comment by NotAShelf** [comment]
I'd generally recommend avoiding NixOS wiki(s). Both the official and the unofficial ones lack any sort of quality assurance, and the information on there is generally out of date.

> After a bit of research, I found that the configuration file format changed in 0.5 version Wireplumber. Lua no longer supported by it.

That is correct, and I seem to have missed WP 0.5 merge entirely - which means my configuration is out of date. I'll take a look at that later, but you probably want to read the migration docs and move the lua config to their new conf format.

**Comment by NotAShelf** [comment]
https://github.com/NotAShelf/nyx/commit/0197527c06215d88e40f80e85555764b101ad901

**Comment by NotAShelf** [comment]
I have updated the configuration again, will push the changes shortly.

**Comment by NotAShelf** [comment]
See if https://github.com/NotAShelf/nyx/commit/3ff41102374958a077bb63d3ec524fa8171538de helps. I haven't paid much attention, but according to `pw-top` and `pw-metadata -n settings 0` the values seem to be inline with my configuration.

**Comment by NotAShelf** [comment]
I stand corrected. the values are not inline, and seem to follow the defaults as you have mentioned.

**Comment by NotAShelf** [comment]
After an hour, I've found the issue. Latest commit should work as intended, cheers.

```
pw-metadata -n settings
Found "settings" metadata 35
update: id:0 key:'log.level' value:'2' type:''
update: id:0 key:'clock.rate' value:'48000' type:''
update: id:0 key:'clock.allowed-rates' value:'[ 48000 ]' type:''
update: id:0 key:'clock.quantum' value:'64' type:''
update: id:0 key:'clock.min-quantum' value:'64' type:''
update: id:0 key:'clock.max-quantum' value:'64' type:''
update: id:0 key:'clock.force-quantum' value:'0' type:''
update: id:0 key:'clock.force-rate' value:'0' type:''
```

**Comment by VeilSilence** [comment]
Well, it take too long for me, but i found the way:
<details><summary>Example</summary>
<p>

```nix
{
  config,
  pkgs,
  lib,
  ...
}: let
  inherit (lib) isx86Linux;
  inherit (lib.modules) mkIf;
  inherit (lib.lists) optionals;

  cfg = config.modules.system.sound;
  dev = config.modules.device;
in {
  config = mkIf (cfg.enable && dev.hasSound) {
    # If the device advertises sound enabled, and pipewire is disabled
    # for whatever reason, we may fall back to PulseAudio to ensure
    # that we still have audio. Although we should always use
    # PipeWire where available.
    hardware.pulseaudio.enable = !config.services.pipewire.enable;

    # Able to change scheduling policies, e.g. to SCHED_RR.
    # Sound servers use RealtimeKit (rtkit) to acquire
    # realtime priority.
    security.rtkit.enable = config.services.pipewire.enable;

    # Enable the threadirqs kernel parameter to reduce audio latency
    # See <https://github.com/musnix/musnix/blob/master/modules/base.nix#L56>
    boot.kernelParams = ["threadirqs"];

    # Enable pipewire and configure it for low latency.
    # PIPEWIRE_LATENCY=256/48000 jack_simple_client to set per application if needed.
    services.pipewire.configPackages = [
      (
        pkgs.writeTextDir "share/pipewire/pipewire.conf.d/92-custom-properties.conf" ''
            context.properties = {
                core.daemon = true              # listening for socket connections
                #core.name   = pipewire-low-latency        # core name and socket name
                default.clock.rate          = 48000
                default.clock.allowed-rates = [ 48000 96000 ]
                default.clock.quantum       = 64
                default.clock.min-quantum   = 64
                default.clock.max-quantum   = 64
                default.clock.quantum-limit = 64
          }
        ''
      )
    ];
  };
}

```

**Comment by VeilSilence** [comment]
Nvm, just saw that you figured.
Small note. I saw that steam also brings his pipewire.conf in `.steam/steam/steamapps/common/SteamLinuxRuntime_sniper/sniper_platform_0.20240415.84603/files/share/pipewire/` 
Something tells me that steam might ignore system settings for pipewire. I didn't test it.
Either way, thank you for assisting.

**Comment by NotAShelf** [comment]
`pkgs.writeTextDir` is certainly an option. I've elected to avoid it, because string interpolation becomes a pain with it. Using extraConfig, albeit finicky, works as intended.
