### ISSUE TITLE
[Security][Kernel] NixOS xanmod missing some kernel modules

### ISSUE THREAD

**Issue by VeilSilence** [NotAShelf/nyx#79]
Greetings. 

As someone ~~who shamelessly stole your~~ was inspired by your Xanmod override config and uses it daily, I thought you might be interested in what I found.
While looking for ways to optimize the Linux kernel for CPU and performance, I decided to compare the NixOS Xanmod kernel config + your override to the CachyOS kernel config and the vanilla Xanmod kernel x86_64-v3 config.

The difference between the NixOS Xanmod kernel config + your override and the Xanmod GitHub kernel config is quite significant—over 3000+ diffs, actually. My investigation is far from over, but you can look at my results [here](https://github.com/VeilSilence/nyx/commit/8a1c3aea249566ed3a99fff39217ec97cc6cb38b).

The most interesting finding from my investigation is that the "Tomoyo" security modules are completely disabled in NixOS xanmod kernel. I saw that you are using `tomoyo` in security/kernel `kernelParams`, so you probably wanna make sure it's working for you, because in my case `sudo dmesg | grep -A 1 -B 1 TOMOYO` output nothing.

**Comment by NotAShelf** [comment]
Hey,

First and foremost, I'm glad my config was able to be any use to you - some days I consider taking it private and comments like this convince me to leave it public for the world to see, despite the potential dangers [of leaving secrets] and the number of license infringements I have already noticed. I should mention that  I am still a newbie when it comes to kernel configuration and that your reports are indeed useful. If I may, I would like to encourage you to keep tinkering and sharing your results. I would be delighted to learn from you.

The difference between NixOS Xanmod and upstream is an interesting find, this config contains several patches that primarily focus on *disabling modules* (and a few on performance), but 3000+ diffs was not a number I was expecting to hear. How did you come across upon this number? More importantly, *why is the diff that large?* NixOS xanmod package is relatively small, and to my knowledge does not provide any additional patches to remove features. 

> The most interesting finding from my investigation is that the "Tomoyo" security modules are completely disabled in NixOS xanmod kernel. I saw that you are using tomoyo in security/kernel kernelParams, so you probably wanna make sure it's working for you, because in my case sudo dmesg | grep -A 1 -B 1 TOMOYO output nothing.

This is also an interesting find, likely a byproduct of my attempt to switch to the hardened kernel and I had *completely* forgotten about my attempt to use TOMOYO in general. Perhaps when you are done, I would like to invite you to make a pull request. For the time being, TOMOYO is not a priority but you have my thanks for pointing that out.

> My investigation is far from over, but you can look at my results [here](https://github.com/VeilSilence/nyx/commit/8a1c3aea249566ed3a99fff39217ec97cc6cb38b).

Last but not least, I want to thank you for sharing your findings with me. Your time and efforts is appreciated.

**Comment by VeilSilence** [comment]
> Hey,
> 
> If I may, I would like to encourage you to keep tinkering and sharing your results. I would be delighted to learn from you.
> 
Thank you for kind words, but I'm not kernel nerd by myself, It's just I decided to remember good old school days on gentoo :) 
>  but 3000+ diffs was not a number I was expecting to hear. How did you come across upon this number? More importantly, _why is the diff that large?_ NixOS xanmod package is relatively small
> 

It's fairly simple to check. Grab and extract current config.gz, then you can go to: [here](https://github.com/xanmod/linux/blob/6.9/CONFIGS/xanmod/gcc/config_x86-64-v3) and do diff between two.
The reason why difference is so big, it's because most of stuff in xanmod kernel comes by default with "y", but in nixos xanmod it's set on "m" instead.

Default xanmod kernel config also have some kernel options, that required only for old CPU or old programs for compatability reasons compared to NixOS xanmod. 
I filtered alot, and now it's less than 1000. Still need alot to filter out.
Some things that enabled in both configs and we can disable:
<details><summary>Details</summary>
<p>

CONFIG_CPU_SUP_INTEL=y
CONFIG_CPU_SUP_HYGON=y
CONFIG_CPU_SUP_CENTAUR=y
CONFIG_CPU_SUP_ZHAOXIN=y

</p>
</details> 

There are few things that I don't understand the reason why it's disabled. Like DMABUF stuff. It's enabled in CachyOS kernel and xanmod by default and was disabled in my case.  

About tomoyo. In order to make tomoyo work, we need kernel options enabled and [tomoyo-userspace-tools](https://aur.archlinux.org/packages/tomoyo-tools)
There is none like that in nixpkgs as far as I can see.

**Comment by NotAShelf** [comment]
It's not disabled, but it's not set either.

```bash
$ zcat /proc/config.gz | rg "RESET_ATTACK_MITIGATION"
# CONFIG_RESET_ATTACK_MITIGATION is not set
```

**Comment by VeilSilence** [comment]
Xanmod github config have this option enabled, but cachyos also not set.
From what I [found](https://cateee.net/lkddb/web-lkddb/RESET_ATTACK_MITIGATION.html) it request free ram before shutdown and reboot.

**Comment by NotAShelf** [comment]
Sorry I completely missed your last message! Thanks Github.

Normally I try to organize my patches via purpose as you probably have noticed. Fitting them in existing categories would be mostly fine I think, since your changes seem to affect mostly existing files. A new file could go a long way if you think it's warranted.

**Comment by NotAShelf** [comment]
Edit: I've just seen your updated fork, the layout seems completely fine to me.

**Comment by VeilSilence** [comment]
> Sorry I completely missed your last message! Thanks Github.
> 
> Normally I try to organize my patches via purpose as you probably have noticed. Fitting them in existing categories would be mostly fine I think, since your changes seem to affect mostly existing files. A new file could go a long way if you think it's warranted.

I thought about mention that here, but I decied to make it more human friendly looking and now that fork outdated a bit.  [here](https://github.com/VeilSilence/Kernel-tunning/blob/main/extra-hardening.md) as for example. 

I'll add more later a bit. Currently, I'm testing different kernels/patches/CPU schedulers/FLTO-Clang/GCC and so on.

Goal is to get understanding, what is the best and in general is it worth to spend time on that.

**SCX-ext** is new cpu [scheduler](https://github.com/sched-ext/scx). 

It shows interesting results actually. [This]( http://arighi.blogspot.com/2024/05/extend-your-battery-life-with.html ) for example, might intrested you, in order to get more battery life on laptop. I cannot verify claims mentioned in this link, because  I cannot measure power consumption accuratly.  If you want, I will provide .patch for **scx** support on kernel side.

This **SCX** CPU schedulers can be started/changed on "fly".
One of my perfomance tests as for example. 22 minute game, x2 replay speed. Camera/cursor movement always same, because I set to show "player point of view".

<details><summary>as for example</summary>
<p>

![Early-results](https://github.com/user-attachments/assets/a9ccc2c6-accf-4517-9073-e73cac32b289)


</p>
</details> 

Phoronix 7zip compress/decompress test also follow this game results. I'm doing more tests than that, It's just so time consuming:/

**Comment by VeilSilence** [comment]
Also want to ask about your kernel override.

`argsOverride` not working at all, because of [bug](https://github.com/NixOS/nixpkgs/issues/314591), I get it, but is `extraStructuredConfig` in `package.nix` passing flags to the kernel on your side?

 Because from my tests, it's not. In other .nix configs, `extraStructuredConfig` passing kernel options correctly, with one note.
 
In `unused.nix` you changed kernel options disabling from `**** = no;` to `CONFIG_**** = no;` I tried on my end, and for me atleast, Nix ignoring them if they formated that way.

**Comment by NotAShelf** [comment]
> I thought about mention that here, but I decied to make it more human friendly looking and now that fork outdated a bit. here updated version.

I will check it out in the upcoming days, currently waiting for an ongoing set of storms to stop knocking out infrastructure left and right.

> SCX-ext is new cpu scheduler.
> It shows interesting results actually. This for example, might intrested you, in order to get more battery life on laptop. I cannot verify claims mentioned in this link, because I cannot measure power consumption accuratly. If you want, I will provide .patch for scx support on kernel side.

I currently don't have the means to test it, but I'd be willing to test a patch on my laptop later on. Some power efficiency on a portable device would *really* be great.

> is extraStructuredConfig in package.nix passing flags to the kernel on your side?

> Because from my tests, it's not. In other .nix configs, from ./config directory, extraStructuredConfig passing kernel options correctly, with one note.

This poses a really weird dilemma because some options don't register if `CONFIG_` prefix is omitted. Similarly, some other options register only if the `CONFIG_` prefix is omitted. Due to my lack of access to my build machine, I couldn't test out my kernel over several rebuilds but I intend to do so soon enough.

**Comment by NotAShelf** [comment]
I've updated my kernel build today. Main difference is that I now build from source (though the way I use patchPhase, I could probably continue overriding. Also removed the CONFIG_ prefix from unused.nix, but it seems like it was not the correct approach.

```bash
zgrep ATALK /proc/config.gz
# CONFIG_ATALK is not set
```

```nix
extraStructuredConfig = mapAttrs (_: mkForce) {
    ATALK = no; # CONFIG_ removed
    # ...
};

This could have something to do with mkForce, but I will need to get back on my main system before I can build my kernel more reliably.
```

**Comment by VeilSilence** [comment]
Found small caveat in your new config:

```nix
  version = "6.9.9";
  suffix = "shelf";
  modDirVersion = pad 3 "${version}-${suffix}";

  xanmod_custom =
    (buildLinux {
      pname = "linux-xanmod";
      inherit version suffix modDirVersion;

      stdenv = gccStdenv;
      src = fetchFromGitHub {
        owner = "xanmod";
        repo = "linux";
        rev = "refs/tags/${version}-${suffix}";
        hash = "sha256-ZEU1RIgJ0ckyITFWZndEzXYwnTF39OviLxL9S5dEea4=";
      };
```
If `suffix` is `shelf` it will try to download refs/tags/$6.9.9-shelf kernel from xanmod github. 
Probably want to change that to normal `xanmod1` suffix, unless there is secret `shelf` kernel  👀 

> I've updated my kernel build today. Main difference is that I now build from source (though the way I use patchPhase, I could probably continue overriding). Also removed the CONFIG_ prefix from unused.nix, but it seems like it was not the correct approach.
> 

> 


Hmm, what exactly do you expect when you set `ATALK = no`? 
Because it indeed disable `ATALK` now.
We don't even need to compile kernel in order to be sure that kernel flag will be disabled.

I'll use your dotfiles as example:


```nix
cd /dotfiles
nix repl
:lf .
nixosConfigurations.<hostname>.config.boot.kernelPackages.kernel.passthru
```

<details><summary>Output</summary>
<p>

```nix
  baseVersion = "6.9.9";
  commonStructuredConfig = { ... };
  config = { ... };
  configEnv = «derivation /nix/store/2ry23mkyamw1dnxgvvnrnkbpsvbp3cwk-linux-xanmod-6.9.9.drv»;
  configfile = «derivation /nix/store/g8z2gww1b7c5n5q256q5pvhvam9mv6cs-linux-config-6.9.9.drv»;
  extraMakeFlags = [ ... ];
  features = { ... };
  isHardened = false;
  isLibre = false;
  isXen = trace: warning: The isXen attribute is deprecated. All Nixpkgs kernels that support it now have Xen enabled.
true;
  isZen = false;
  kernelAtLeast = «lambda versionAtLeast @ /nix/store/qmh8bas1qni03drm0lnjas2azh7h87cn-source/lib/strings.nix:717:24»;
  kernelOlder = «lambda versionOlder @ /nix/store/qmh8bas1qni03drm0lnjas2azh7h87cn-source/lib/strings.nix:705:22»;
  kernelPatches = [ ... ];
  modDirVersion = "6.9.9-shelf";
  moduleBuildDependencies = [ ... ];
  pname = "linux-xanmod";
  src = «derivation /nix/store/1k6c808d4mbknip5n4g7vspwmkx6icav-source.drv»;
  stdenv = «derivation /nix/store/3j3885jjszgd49vn6jm49jqg1qbiy44i-stdenv-linux.drv»;
  structuredExtraConfig = { ... };
  tests = [ ... ];
  version = "6.9.9";
  withRust = false;
  ```

</p>
</details> 

`configfile = «derivation` in order to check if flag we need was disabled:
```shell
cat /nix/store/g8z2gww1b7c5n5q256q5pvhvam9mv6cs-linux-config-6.9.9.drv | grep -o 'ATALK n'
ATALK n
```

**Comment by NotAShelf** [comment]
Oh that's funny. Since I have not updated the hash, consecutive rebuilds pulled the latest hash I've used. Guess that teaches me.

**Comment by NotAShelf** [comment]
> Hmm, what exactly do you expect when you set ATALK = no?

`... is not set` leads me to believe the value is not modified - though I haven't experimented with a traditionally built kernel, so I have no clue on what to expect.

**Comment by VeilSilence** [comment]
> > Hmm, what exactly do you expect when you set ATALK = no?
> 
> `... is not set` leads me to believe the value is not modified - though I haven't experimented with a traditionally built kernel, so I have no clue on what to expect.

Found [this](https://lore.kernel.org/all/20220226123755.85213-1-masahiroy@kernel.org/) in official kernel list.

**Comment by NotAShelf** [comment]
That was a good read.

I could try fetching and applying the patch, but it'd probably be a redundant change. Though I now know disabled options work as expected.

**Comment by VeilSilence** [comment]
Something not right with patch applying.

Let's try to add `bridge_stp_helper` in `kernelPatches`  for example.
In `configEnv` derivation, we can see something like that:

<details><summary>configEnv</summary>
<p>

```nix

["out"])],["/nix/store/mnlqwys9dxznjcvq4w3s0435s9ql8qv8-bridge-stp-helper.patch",....

("outputs","out dev"),("patches","/nix/store/mnlqwys9dxznjcvq4w3s0435s9ql8qv8-bridge-stp-helper.patch

```

</p>
</details>



Now, I tried to add  xanmod-sched-ext, and verify that in `configEnv` patch appear:

<details><summary>configEnv</summary>
<p>

```nix

["out"]),("/.....","/nix/store/mr5sk5qswh2z31l1s9b6nakyi3yz8snh-xanmod-sched-ext.patch"

("outputs","out dev"),("patches","/nix/store/mnlqwys9dxznjcvq4w3s0435s9ql8qv8-bridge-stp-helper.patch /nix/store/mr5sk5qswh2z31l1s9b6nakyi3yz8snh-xanmod-sched-ext.patch

```

</p>
</details>

Looks good. Now, let's try to change generation and check build output:

<details><summary>Build output</summary>
<p>

```shell
linux-config> Running phase: unpackPhase
linux-config> unpacking source archive /nix/store/xrf1gs1fhk5a2470gvs5hl7cvrzb4728-source
linux-config> calling 'unpackCmd' function hook '_defaultUnpack' /nix/store/xrf1gs1fhk5a2470gvs5hl7cvrzb4728-source
linux-config> source root is source
linux-config> calling 'postUnpack' function hook '_updateSourceDateEpochFromSourceRoot'
linux-config> Running phase: patchPhase
linux-config> applying patch /nix/store/mnlqwys9dxznjcvq4w3s0435s9ql8qv8-bridge-stp-helper.patch
linux-config> patching file net/bridge/br_private.h
linux-config> Hunk #1 succeeded at 51 with fuzz 2 (offset 12 lines).
linux-config> applying patch /nix/store/mbz5gln1q4swlzmqs2399br98qjif9kn-request-key-helper.patch
linux-config> patching file security/keys/request_key.c
linux-config> Hunk #1 succeeded at 117 (offset 3 lines).
linux-config> applying patch /nix/store/mr5sk5qswh2z31l1s9b6nakyi3yz8snh-xanmod-sched-ext.patch
linux-config> patching file Documentation/scheduler/index.rst
linux-config> patching file Documentation/scheduler/sched-ext.rst
linux-config> patching file MAINTAINERS
linux-config> patching file drivers/tty/sysrq.c
linux-config> patching file include/asm-generic/vmlinux.lds.h
linux-config> patching file include/linux/cgroup.h
linux-config> patching file include/linux/sched.h
linux-config> patching file include/linux/sched/ext.h
linux-config> patching file include/linux/sched/task.h
linux-config> patching file include/trace/events/sched_ext.h
linux-config> patching file include/uapi/linux/sched.h
linux-config> patching file init/init_task.c
linux-config> patching file kernel/Kconfig.preempt
linux-config> patching file kernel/fork.c
linux-config> patching file kernel/sched/build_policy.c
linux-config> patching file kernel/sched/core.c
linux-config> patching file kernel/sched/cpufreq_schedutil.c
linux-config> patching file kernel/sched/debug.c
linux-config> patching file kernel/sched/ext.c
linux-config> patching file kernel/sched/ext.h
linux-config> patching file kernel/sched/fair.c
linux-config> patching file kernel/sched/idle.c
linux-config> patching file kernel/sched/sched.h
linux-config> patching file lib/dump_stack.c
linux-config> patching file tools/Makefile
linux-config> patching file tools/sched_ext/.gitignore
linux-config> patching file tools/sched_ext/Makefile
linux-config> patching file tools/sched_ext/README.md
linux-config> patching file tools/sched_ext/include/bpf-compat/gnu/stubs.h
linux-config> patching file tools/sched_ext/include/scx/common.bpf.h
linux-config> patching file tools/sched_ext/include/scx/common.h
linux-config> patching file tools/sched_ext/include/scx/compat.bpf.h
linux-config> patching file tools/sched_ext/include/scx/compat.h
linux-config> patching file tools/sched_ext/include/scx/user_exit_info.h
linux-config> patching file tools/sched_ext/scx_central.bpf.c
linux-config> patching file tools/sched_ext/scx_central.c
linux-config> patching file tools/sched_ext/scx_qmap.bpf.c
linux-config> patching file tools/sched_ext/scx_qmap.c
linux-config> patching file tools/sched_ext/scx_show_state.py
linux-config> patching file tools/sched_ext/scx_simple.bpf.c
linux-config> patching file tools/sched_ext/scx_simple.c
linux-config> patching file tools/testing/selftests/sched_ext/.gitignore
linux-config> patching file tools/testing/selftests/sched_ext/Makefile
linux-config> patching file tools/testing/selftests/sched_ext/config
linux-config> patching file tools/testing/selftests/sched_ext/create_dsq.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/create_dsq.c
linux-config> patching file tools/testing/selftests/sched_ext/ddsp_bogus_dsq_fail.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/ddsp_bogus_dsq_fail.c
linux-config> patching file tools/testing/selftests/sched_ext/ddsp_vtimelocal_fail.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/ddsp_vtimelocal_fail.c
linux-config> patching file tools/testing/selftests/sched_ext/dsp_local_on.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/dsp_local_on.c
linux-config> patching file tools/testing/selftests/sched_ext/enq_last_no_enq_fails.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/enq_last_no_enq_fails.c
linux-config> patching file tools/testing/selftests/sched_ext/enq_select_cpu_fails.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/enq_select_cpu_fails.c
linux-config> patching file tools/testing/selftests/sched_ext/exit.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/exit.c
linux-config> patching file tools/testing/selftests/sched_ext/exit_test.h
linux-config> patching file tools/testing/selftests/sched_ext/hotplug.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/hotplug.c
linux-config> patching file tools/testing/selftests/sched_ext/hotplug_test.h
linux-config> patching file tools/testing/selftests/sched_ext/init_enable_count.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/init_enable_count.c
linux-config> patching file tools/testing/selftests/sched_ext/maximal.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/maximal.c
linux-config> patching file tools/testing/selftests/sched_ext/maybe_null.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/maybe_null.c
linux-config> patching file tools/testing/selftests/sched_ext/maybe_null_fail_dsp.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/maybe_null_fail_yld.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/minimal.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/minimal.c
linux-config> patching file tools/testing/selftests/sched_ext/prog_run.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/prog_run.c
linux-config> patching file tools/testing/selftests/sched_ext/reload_loop.c
linux-config> patching file tools/testing/selftests/sched_ext/runner.c
linux-config> patching file tools/testing/selftests/sched_ext/scx_test.h
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_dfl.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_dfl.c
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_dfl_nodispatch.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_dfl_nodispatch.c
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_dispatch.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_dispatch.c
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_dispatch_bad_dsq.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_dispatch_bad_dsq.c
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_dispatch_dbl_dsp.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_dispatch_dbl_dsp.c
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_vtime.bpf.c
linux-config> patching file tools/testing/selftests/sched_ext/select_cpu_vtime.c
linux-config> patching file tools/testing/selftests/sched_ext/test_example.c
linux-config> patching file tools/testing/selftests/sched_ext/util.c
linux-config> patching file tools/testing/selftests/sched_ext/util.h
linux-config> applying patch /nix/store/23728y7zgh1jb55kpwxv5qnjbq0ykca6-randstruct-provide-seed-5.19.patch
linux-config> patching file scripts/gen-randstruct-seed.sh
linux-config> evaling implicit 'postPatch' string hook
linux-config> patching script interpreter paths in scripts/ld-version.sh
linux-config> scripts/ld-version.sh: interpreter directive changed from "#!/bin/sh" to "/nix/store/m101dg80ngyjdb02g6jwy80sr7kzj26g-bash-5.2p26/bin/sh"
linux-config> substituteStream() in derivation linux-config-6.10.0: WARNING: '--replace' is deprecated, use --replace-{fail,warn,quiet}. (file 'scripts/gen-randstruct-seed.sh')
linux-config> patching script interpreter paths in scripts
```

</p>
</details>

Note that `randstruct-provide-seed` patch is not mine, but NixOS.
I didn't set in `kernelPatches` to install that patch.
Again, looks like everything patched succesfully.

But, after compile kernel, I couldn't start any SCX schedulers.
Let's check if kernel options like `SCHED_CLASS_EXT` set=y then:

```shell
zcat /proc/config.gz | grep -i "SCHED_CLASS_EXT"


```

`CHED_CLASS_EXT` not even "exist" in config.gz.

Normaly, if option is disabled, it would return like "option not set", but in this case, it's clear something was not right during "patch" phase.

I patched xanmod kernel "manually", pushed  patched kernel to mine [test](https://github.com/VeilSilence/Custom-Xanmod) repository, and then changed owner/rep/etc in kernel config.

<details><summary>Details</summary>
<p>

```nix
src = fetchFromGitHub {
        owner = "VeilSilence";
        repo = "Custom-Xanmod";
        rev = "refs/tags/${version}.Nix";
        hash = "sha256-PrNzIpq3TbAddU3+qY/lOdiDZI3D5bNlbenwNYJC3dA=";
};

```

</p>
</details>


After compile and reboot:

```shell
zcat /proc/config.gz | grep -i "SCHED_CLASS_EXT"
CONFIG_SCHED_CLASS_EXT=y
```

SCX-schedulers also works as intended.

Honestly, not sure what can cause such behaviour. Patch is correct, something wrong with patch phase, but I'm not sure what exactly wrong..

**Comment by NotAShelf** [comment]
Looking into the manual config builder, looks like kernelPatches are passed verbatim to manualConfig and mapped to the `patches = [ ]` list one by one. IN which case, it *should* apply - unless the patch fails because it conflicts with prior patches (e.g. bridge helper?)

**Comment by VeilSilence** [comment]
The problem was at last identified. 
```nix
    .overrideAttrs {
      patchPhase = ''
        runHook prePatch

        # Without this override, buildLinux forces me to use the value set in
        # localversion which, as you can tell, is xanmod1. Replace it with my
        # own custom suffix to indicate this is a custom build.
        # ...and for bragging rights.
        substituteInPlace localversion \
          --replace-fail "xanmod1" "${customSuffix}"

        runHook postPatch
      '';      
  ```
  
 For some reason, this override breaks patching completly.
 I decided to just nuke `localversion` with patch, add `LOCALVERSION = freeform "-${customSuffix}";` and removed override. 
 
 
<details><summary>patch</summary>
<p>

```shell
From dc3fedfc862fc6a6b2a26e5009b0295b181ba57d Mon Sep 17 00:00:00 2001
From: VeilSilence <BoneFeaR@proton.me>
Date: Sat, 20 Jul 2024 21:08:24 +0300
Subject: [PATCH] Nuke -xanmod in localversion

---
 localversion | 1 -
 1 file changed, 1 deletion(-)

diff --git a/localversion b/localversion
index c21af2f75..e69de29bb 100644
--- a/localversion
+++ b/localversion
@@ -1 +0,0 @@
--xanmod1
--
2.45.2


``` 

</p>
</details>

**Comment by NotAShelf** [comment]
Oh I know what the issue, I'll push a fix real quick.

**Comment by NotAShelf** [comment]
https://github.com/NotAShelf/nyx/commit/d55c6235adcb183e065ba3fe0cb069d24ffa05d0

This should fix the issue with the patchPhase overriding the old one. Completely forgot about this one.

**Comment by VeilSilence** [comment]
I tested your new variant and it works as expected.
Both options is valid I think: override and modify `.localversion` with patch.

Scrying over ClearLinux project ( Intel devs linux kernel ), and there are few interesting things also.

For example: [Build TPM](https://github.com/clearlinux-pkgs/linux/commit/fa9434429796cb873bdd8458341ee5c7065c6b11) drivers into kernel so it can decrypt the root filesystem, [extra flags optimizations](https://github.com/clearlinux-pkgs/linux/blob/main/0162-extra-optmization-flags.patch),  and others.
All patches have comment for reason behind changes, but need to keep in mind that xanmod already ship some of this patches already. 

In the end, looks like NixOS default kernel also imported few otpions from ClearLinux?

For example: `CONFIG_RANDOMIZE_MEMORY_PHYSICAL_PADDING=0x1`. ClearLinux also set it at `0x1`, but xanmod github .config and cachyos use `"0xa"`.

`CLOCKSOURCE_WATCHDOG_MAX_SKEW_US = "100";`  but in this case, NixOS set it at 125, when other kernels set it at 100.
Same thing for `TPM` changes I mentioned earlier. ClearLinux, xanmod github, cachyos also build them in kernel, but NixOS build them as `m`

**Comment by NotAShelf** [comment]
> For example: [Build TPM](https://github.com/clearlinux-pkgs/linux/commit/fa9434429796cb873bdd8458341ee5c7065c6b11) drivers into kernel so it can decrypt the root filesystem, [extra flags optimizations](https://github.com/clearlinux-pkgs/linux/blob/main/0162-extra-optmization-flags.patch), and others.
All patches have comment for reason behind changes, but need to keep in mind that xanmod already ship some of this patches already.

I am not very interested in TPM support in my kernel. Even if it did, I would not use TPM to decrypt filesystems. Flag optimizations are interesting however, I will wait until I can get LLVM builds working until I mess with them.

> In the end, looks like NixOS default kernel also imported few otpions from ClearLinux?

> For example: CONFIG_RANDOMIZE_MEMORY_PHYSICAL_PADDING=0x1. ClearLinux also set it at 0x1, but > xanmod github .config and cachyos use "0xa".

I've also noticed this while borrowing kernel configuration from the linux-libre kernel. While still a dream, I might look into disabling *all* default options and try to build entirely from the config provided to the package. 

I intend to go over ClearLinux and TKG patches at some point to borrow whichever may be necessary, but some (if not most) patches have sub-par documentation regarding their behaviour or motivations.

**Comment by NotAShelf** [comment]
I've managed to build via LLVM after some trial and error, though the final result was disappointing at best. 45 minute build times as opposed to my 30~ with gccStdenv.

That said, I will be archiving this repository very soon. I don't know what that implies for issues, but I imagine they will become unavailable. Should you wish to discuss kernel development any further, you can reach me on Discord as `@notashelf` or over matrix as `@raf:notashelf.dev`. We can also use e-mail, but that's a subpar channel at best.

**Comment by VeilSilence** [comment]
> 
> I am not very interested in TPM support in my kernel. Even if it did, I would not use TPM to decrypt filesystems. Flag optimizations are interesting however, I will wait until I can get LLVM builds working until I mess with them.

Understandable. Everything that goes from manufacter cannot be trusted.  As for recent [example](https://www.binarly.io/blog/pkfail-untrusted-platform-keys-undermine-secure-boot-on-uefi-ecosystem) .
In LSM, google engineer also found [vulnerability](https://git.kernel.org/pub/scm/linux/kernel/git/mic/linux.git/commit/?h=next&id=39705a6c29f8a2b93cf5b99528a55366c50014d1)

> I intend to go over ClearLinux and TKG patches at some point to borrow whichever may be necessary, but some (if not most) patches have sub-par documentation regarding their behaviour or motivations.

Agree. There is also maintain burden with patches. I'm trying to be picky with the patches and verify the claims if possible, otherwise it's just cargo cult in the end.

**Comment by VeilSilence** [comment]
> I've managed to build via LLVM after some trial and error, though the final result was disappointing at best. 45 minute build time as opposed to my 30~ with gccStdenv.
>  


Currently, I'm building kernel with this LLVM stdenv "helper".

<details><summary>LLVMstdenv</summary>
<p>

```nix
{
  llvmPackages_17,
  patchelf,
  overrideCC,
}:
# https://github.com/oluceps/nyx/blob/43941a1cd70f282597611e7fe6c82f90e584f570/pkgs/linux-cachyos/kernel.nix#L19
# https://github.com/xddxdd/nur-packages/blob/94451913d7b86b8bb43d7e914cf76da8b7edf507/pkgs/lantian-linux-xanmod/helpers.nix#L10
let
  noBintools = {
    bootBintools = null;
    bootBintoolsNoLibc = null;
  };
  hostLLVM = llvmPackages_17.override noBintools;
  buildLLVM = llvmPackages_17.override noBintools;

  mkLLVMPlatform = platform:
    platform
    // {
      linux-kernel =
        platform.linux-kernel
        // {
          makeFlags =
            (platform.linux-kernel.makeFlags or [])
            ++ [
              "LLVM=1"
              "LLVM_IAS=1"
              "CC=${buildLLVM.clangUseLLVM}/bin/clang"
              "LD=${buildLLVM.lld}/bin/ld.lld"
              "HOSTLD=${hostLLVM.lld}/bin/ld.lld"
              "AR=${buildLLVM.llvm}/bin/llvm-ar"
              "HOSTAR=${hostLLVM.llvm}/bin/llvm-ar"
              "NM=${buildLLVM.llvm}/bin/llvm-nm"
              "STRIP=${buildLLVM.llvm}/bin/llvm-strip"
              "OBJCOPY=${buildLLVM.llvm}/bin/llvm-objcopy"
              "OBJDUMP=${buildLLVM.llvm}/bin/llvm-objdump"
              "READELF=${buildLLVM.llvm}/bin/llvm-readelf"
              "HOSTCC=${hostLLVM.clangUseLLVM}/bin/clang"
              "HOSTCXX=${hostLLVM.clangUseLLVM}/bin/clang++"
            ];
        };
    };

  stdenv' = overrideCC hostLLVM.stdenv hostLLVM.clangUseLLVM;
in
  stdenv'.override (old: {
    hostPlatform = mkLLVMPlatform old.hostPlatform;
    buildPlatform = mkLLVMPlatform old.buildPlatform;
    extraNativeBuildInputs = [hostLLVM.lld patchelf];
  })
```


</p>
</details> 

However, I didn't found the way to fix kernel module building ( like zenpower module as for example ).

I also noticed slower compile time, but it's says that it's expected with link time optimization. Also for some reason, llvm18 fail to compile kernel for me.

> That said, I will be archiving this repository very soon. I don't know what that implies for issues, but I imagine they will become unavailable. Should you wish to discuss kernel development any further, you can reach me on Discord as `@notashelf` or over matrix as `@raf:notashelf.dev`. We can also use e-mail, but that's a subpar channel at best.
> 
> Edit: should you wish not to continue this discussion, I thank you regardless. Be well.


I will continue to experimenting with kernel/kernel flags and will publish results in my repo at the end. 

About your decision to move this repo in archive: whatever the reasons is, I wanna say thank you for everything.  
i'm also on hyprland server, I just didn't wanna bother you. I'm trying as much as possible to find myself answers/solutions, even if it will take alot of time searching everything.

With regards.
