### ISSUE TITLE
 Can I borrow the current config, slap my name on it, and pretend I did all the hard work?

### ISSUE THREAD

**Issue by FrothyMarrow** [NotAShelf/nyx#83]
Since you have abandoned it anyway.

**Comment by NotAShelf** [comment]
![5gt4r5.png](https://github.com/user-attachments/assets/44e1ae22-f962-4225-9583-d09f7d62d6a9)

**Comment by NotAShelf** [comment]
Get in line

**Comment by eclairevoyant** [comment]
Just get a copilot subscription, microsoft has already done so :money_with_wings:

**Comment by FrothyMarrow** [comment]
> Just get a copilot subscription, microsoft has already done so 💸

<img width="465" alt="Screenshot 2024-08-02 at 12 01 50 AM" src="https://github.com/user-attachments/assets/38db56e8-f2be-4d87-ad8e-66f4841ba18a">

It's not working because apparently it's not a robot...
